import json, sys
TVT="research/raw_ravenor/tvt_chars.txt (https://tvtropes.org/pmwiki/pmwiki.php/Characters/Ravenor)"
TVTLIT="research/raw_ravenor/src1.txt (https://tvtropes.org/pmwiki/pmwiki.php/Literature/Ravenor)"
ATT="research/raw_ravenor/src10.txt (https://allthetropes.org/wiki/Ravenor)"
LEXR="https://wh40k.lexicanum.com/wiki/Gideon_Ravenor (copy: research/raw_bequin/lex_Gideon_Ravenor.txt)"
DE=lambda p:f"https://wh40k-de.lexicanum.com/wiki/{p} (read via web search summary; direct fetch blocked)"
EN=lambda p:f"https://wh40k.lexicanum.com/wiki/{p} (read via web search summary; direct fetch blocked)"
POL="research/raw_appearance/rav_polaris_raveodpad.htm (http://www.polarissf.cz/souborPOLAR/raveodpad.htm, Czech excerpt of Ravenor Rogue)"
NOVEL=lambda b:f"{b} novel text, as quoted in web search result snippets (not independently fetched)"
def rec(id, form="human", sex="unknown", age="unknown", build="unknown", skin="unknown", hc="unknown", hs="unknown",
        fh="unknown", ec="unknown", glow=False, marks=(), attire=(), carries=(), palette=(), described="none", summary="", ev=()):
    return dict(id=id, form=form, sex=sex, age=age, build=build, skin=skin, hair=dict(color=hc, style=hs), facialHair=fh,
                eyes=dict(color=ec, glow=glow), marks=list(marks), attire=list(attire), carries=list(carries), palette=list(palette),
                described=described, summary=summary, evidence=[dict(claim=c, source=s) for c,s in ev])
A=[
rec("carl-thonius", sex="male", age="young", build="slight", skin="pale", hc="blonde", hs="unknown", fh="none",
    attire=["finery","long-coat"], carries=["pistol"], palette=["#8b1a1a","#111111","#8a8a8a"], described="well",
    summary="Foppish, impeccably dressed young interrogator with heavy blond hair and a face powdered white; seen in a tailored red velvet suit, black buckled shoes and a grey plastek raincoat. After his right arm is severed and reattached he wears dozens of rings on that hand, dresses less foppishly and has dyed his hair black by Ravenor Rogue; when Slyte manifests he glows from within, skeleton visible, right forearm flayed to black bone with talons.",
    ev=[("heavy blond hair; average build per de-Lexicanum; red velvet suit, black buckled shoes, grey plastek-oxide raincoat, face powdered white, handkerchief", DE("Carl_Thonius")),
        ("always poised, well-groomed and impeccably dressed (The Dandy)", TVT),
        ("extremely thin, looks weak (Waif-Fu); conflicts with de-Lexicanum 'average build'", TVT),
        ("dyed his normally blonde hair black by start of Ravenor Rogue; up to thirty rings on right hand", TVT),
        ("Slyte form: body lit from within, skeleton visible, right arm flesh peels back, fingers become talons", TVT),
        ("carries a Hecuter 6 pistol", TVT)]),
rec("patience-kys", sex="female", age="adult", build="slight", hc="black", hs="tied", fh="none", ec="green",
    attire=["bodyglove"], carries=["blades-floating"], described="well",
    summary="Tall, thin but athletic telekine with angular features, emerald-green eyes and raven-black hair worn up in a chignon held by two silver pins that double as kineblades; usually in a tight, lightly armoured bodyglove. In Pariah she first appears disguised as a nun ('Sister Tharpe'); no separate later physical description was found.",
    ev=[("tall, thin, athletic, angular features, emerald-green eyes, raven-black hair in a chignon with two silver hairpins, tight lightly-armoured bodygloves (cites Ravenor ch.1)", DE("Patience_Kys")),
        ("almost never seen without a tight bodyglove; kineblades worn in her hair or up her sleeve", TVT),
        ("tall but slight, physically unimposing (Waif-Fu)", TVT),
        ("in Pariah disguised as a Sister ('Sister Tharpe') at Beta's orphanage", "research/raw_bequin/jm_pariah3.txt; https://bbs.stardestroyer.net/viewtopic.php?t=156874 (search summary)")]),
rec("slyte", form="daemon", build="massive", described="partial",
    summary="Daemon that possesses Carl Thonius: its harbinger form is Thonius glowing red from within, skin translucent and bones showing, the right forearm stripped to coal-black bone ending in claws. Its true manifestation in Ravenor Rogue is a mountain-sized, ever-growing mass of black flesh with mouths and tentacles hundreds of metres long; its touch rots and mummifies.",
    ev=[("red light from within, translucent skin, bones visible; forearm flesh withdraws exposing coal-black bones with claws; full form a huge mass of tissue with tentacle-like pseudopods hundreds of metres long", DE("Slyte")),
        ("true form: towering mountain of filthy black flesh covered in mouths and tentacles; humanoid harbinger has visible skeleton and fleshless oversized right arm", TVT),
        ("first manifestation as a black skeletal humanoid glowing with a baleful red aura", TVTLIT)]),
rec("zael", sex="male", age="child", described="none",
    summary="Flect-addicted hive street boy of about twelve to fourteen; no concrete physical description (hair, eyes, clothes) was found in accessible sources. He later becomes the Grey Knight Hyperion (outside these books).",
    ev=[("a boy about 14 years old, addicted to flects", LEXR),
        ("novel gives his age as twelve; on the streets since eleven", NOVEL("Ravenor")),
        ("street urchin", TVT)]),
rec("zygmunt-molotch", sex="male", age="adult", build="slight", fh="none", marks=["wards"], palette=["#111111"], described="partial",
    summary="Slim, dignified, beardless man dressed in black whose face is quite handsome but strangely asymmetrical, with hexagrammic wards tattooed on his scalp under the hairline (Ravenor Rogue). In Ravenor Returned, disguised as Lord-Governor Barazan, his face is burn-scarred like melted wax, healed by the Enuncia ritual at that book's end.",
    ev=[("slim man, dignified, dressed in black, beardless face, quite handsome but strangely asymmetrical (Ravenor Rogue, Czech edition)", POL),
        ("face described as handsome but completely asymmetrical", TVT),
        ("face resembling melted wax as the Diadochoi; scars healed by the ritual", TVT),
        ("hexagrammic wards tattooed on his scalp under the hairline (forum quote of Ravenor Rogue)", "https://bbs.stardestroyer.net/viewtopic.php?t=106944 (search summary)")]),
rec("angharad-esw-sweydyr", sex="female", age="young", build="athletic", hs="braided", attire=["bodyglove"], carries=["sword"], described="partial",
    summary="Very tall (about two metres) Carthaen swordswoman, the image of her aunt Arianhrod, with hair plaited with beads and an elaborately shaped bodysuit; wields the force sword Evisorex. Hair colour not confirmed for her specifically.",
    ev=[("tall, hair braided bead-like, elaborately shaped bodysuit, sword Evisorex", DE("Angharad_Esw_Sweydyr")),
        ("two metres tall with hair plaited with beads; strikingly like her aunt", EN("Angharad_Esw_Sweydyr")),
        ("spitting image of her late aunt Arianhrod; 'Built for fighting'", TVT)]),
rec("jader-trice", sex="male", build="slight", attire=["finery"], described="partial",
    summary="Slender, well-dressed and well-groomed Grand Provost of the Ministry of Sub-Sector Trade; no hair, eye or face details found.",
    ev=[("described as having a slender build (Lean and Mean)", TVT), ("well dressed and well groomed (A Man of Wealth and Taste)", TVT)]),
rec("lucius-worna", sex="male", build="massive", hc="white", hs="shaven", marks=["scar-face"], attire=["power-armour"], palette=["#eae3d8"], described="well",
    summary="Huge, brutish bounty hunter whose face is one solid mass of scar tissue, ears and nose worn to lumps of gristle; head shaved except for a bleached stripe; wears polished mother-of-pearl power armour without a helmet.",
    ev=[("face one massive scar; ears and nose eroded lumps of gristle", EN("Lucius_Worna")),
        ("head shaved apart from a bleached stripe", NOVEL("Ravenor Returned")),
        ("shock of white hair; polished mother-of-pearl power armour; face almost solid scar tissue; big, physically imposing", TVT),
        ("pearl-coloured power armour, huge, no helmet", "https://1d6chan.miraheze.org/wiki/Gideon_Ravenor (via research/raw_ravenor grep)")]),
rec("maud-plyton", sex="female", age="young", build="heavy", hc="black", hs="cropped", attire=["uniform"], carries=["rifle"], palette=["#8b8455"], described="well",
    summary="Ex-Magistratum marshal with a large, slightly thickset frame at odds with very delicate, pretty, youthful features; dark hair cropped short (a Magistratum habit); in Ravenor Rogue wears a shabby khaki zip-front flight suit, heavy combat boots and white undervest or Navy surplus fatigues; favours a shotgun.",
    ev=[("large, slightly thickset frame, very delicate features; dark hair cropped short (Magistratum regulation); khaki flight suit, combat boots, white undervest; Navy surplus fatigues", NOVEL("Ravenor Rogue")),
        ("pretty, youthful face but built like a bruiser; shotgun is her weapon of choice", TVT),
        ("cute facial features clashing with no-nonsense appearance", LEXR)]),
rec("orfeo-culzean", sex="male", age="older", build="heavy", hc="black", hs="short", fh="beard", attire=["robes","finery"], described="partial",
    summary="Portly, middle-aged antiquarian with sleek swept-back black hair and a finely trimmed beard, dressed in comfortable robes of fine fabric.",
    ev=[("portly middle-aged man, slicked-back black hair, finely trimmed beard, comfortable robes of mostly fine fabric", DE("Orfeo_Culzean"))]),
rec("patrik-belknap", sex="male", attire=["uniform","long-coat"], carries=["rifle"], palette=["#111111"], described="partial",
    summary="Ex-Guard medicae, slimmer than Nayl, in black army combat fatigues and a long flapping leather coat that gives him a piratical look; carries a black leather medical bag and a battered old Guard lascarbine with folding stock.",
    ev=[("slimmer than Nayl; black army fatigues; long leather coat; black leather doctor's bag; old lascarbine with skeletal folding stock", NOVEL("Ravenor Returned")),
        ("six years in the Imperial Guard", TVT)]),
rec("sholto-unwerth", sex="male", build="heavy", fh="beard", attire=["bodyglove","armour-light"], palette=["#6b1015"], described="partial",
    summary="Short, stocky, dwarf-like and bearded shipmaster (claims Squat ancestry), usually in a dark red bodysuit with attached metal plates, accompanied by his elquon manhound Fyflank; loses four fingers to torture in Ravenor Returned.",
    ev=[("short, stocky, akin to a dwarf; dark red bodysuit with metal plates; pet elquon", DE("Sholto_Unwerth")),
        ("explains to Belknap why he is so short and bearded (Squat blood)", TVTLIT),
        ("has four fingers cut off", TVT)]),
rec("wystan-frauka", sex="male", build="heavy", carries=["lho-stick"], described="partial",
    summary="Big, bored, chain-smoking blank, always with a lho-stick, with a psychic limiter/inhibitor set in his neck; Kys privately thinks him reasonably good-looking. No hair or eye details found.",
    ev=[("big, chain-smoking; inhibitor in his neck", LEXR),
        ("constantly smokes lho-sticks; reasonably good looking per Kys; wears a limiter", TVT)]),
rec("zeph-mathuin", sex="male", age="adult", build="massive", skin="dark", hc="black", hs="braided", ec="red", glow=True, marks=["augmetic-eyes","augmetic-arm"], described="well",
    summary="Very large, heavily muscled dark-skinned ex-bounty hunter with long black dreadlocks/braided strands, glowing red augmetic eyes and a chromed augmetic left arm that interfaces with his six-barrelled rotator cannon, worn with a counterweight support frame.",
    ev=[("dark-skinned, big and very muscular; black hair in long braided strands; red glowing bionic eyes; whole left arm augmetic and chrome-armoured", DE("Zeph_Mathuin")),
        ("lengthy dreadlocks; red glowing augmetic eyes; augmetic left arm; rotator cannon with support frame", TVT),
        ("fandom says right arm connects to autocannon (conflict; left preferred)", LEXR)]),
rec("bartol-siskind", sex="male", described="none", summary="Shipmaster of the Allure and minor Cognitae-descended trader; no physical description found.",
    ev=[("master of the Allure, Cognitae third generation", "research/raw_ravenor/src2.txt; web search summary of Lexicanum")]),
rec("cynia-preest", sex="female", age="older", hc="blonde", hs="short", marks=["augmetic-cranial"], attire=["bodyglove","robes"], palette=["#c9a227","#8b1a1a"], described="well",
    summary="284-year-old shipmistress described as both robust and thin, matronly; bleached hair spiked up, heavy mascara and big dangling earrings, a golden bodysuit under a red velvet robe, and fine circuitry running across the left side of her face.",
    ev=[("age 284, robust yet thin and matronly; golden bodysuit under red velvet robe; bleached spiked hair; heavy mascara, large dangling earrings; fine circuitry on left side of face (cites Ravenor ch.1)", DE("Cynia_Preest")),
        ("'kind of hot but super old, 200+ years'", "https://1d6chan.miraheze.org/wiki/Gideon_Ravenor (via research/raw_ravenor grep)")]),
rec("feaver-skoh", sex="male", described="none", summary="Xenos hunter running a family game-hunting business; no physical description found.",
    ev=[("xenos hunter, brother Fernan", "research/raw_ravenor/src2.txt (lonepilgrim synopsis)")]),
rec("gall-ballack", sex="male", hc="white", hs="long", marks=["augmetic-arm"], described="partial",
    summary="Interrogator and Cognitae mole marked by long white hair framing his face; after Angharad cuts off his hand he wears an augmetic replacement hiding a one-shot laspistol.",
    ev=[("much mention of his white hair (White Hair, Black Heart); hand hacked off and replaced with a cybernetic prosthetic", TVT),
        ("face framed by long white hair at introduction", NOVEL("Ravenor Rogue"))]),
rec("iosob", sex="female", age="young", build="slight", skin="pale", hc="blonde", hs="cropped", attire=["hood"], described="partial",
    summary="Hooded Wych House housekeeper who turns out to be a girl barely into adolescence, with a thin, pale face fringed by cropped blonde hair and grazed, bleeding fingers clutching her key.",
    ev=[("hooded; a young girl barely into adolescence; thin pale face fringed by cropped blonde hair", NOVEL("Ravenor Rogue"))]),
rec("kizary-thekla", described="none", summary="Rogue trader captain of the Oktober Country; no physical description found.",
    ev=[("rogue trader, Oktober Country", DE("Oktober_Country_(Schiff)"))]),
rec("leyla-slade", sex="female", age="young", build="athletic", hc="blonde", hs="short", carries=["pistol"], described="partial",
    summary="Culzean's off-world bodyguard: a tall young woman built like a swimmer, with short fair hair and a hard, unforgiving face; carries a Hecuter 5 pistol (including daemon-summoning rounds).",
    ev=[("off-world girl, tall, swimmer's build, short fair hair, hard unforgiving expression; her Hecuter 5", POL),
        ("magazine of daemon-summoning handgun bullets", TVT)]),
rec("lomer-kinsky", sex="male", described="none", summary="Powerful, crude Ministry psyker; no physical description found in accessible sources.",
    ev=[("powerful psyker; neck snapped by Frauka", TVT)]),
rec("madsen", sex="female", described="none", summary="Lusinda Madsen, Ministry tech-adept and code writer leading the team; no physical description found.",
    ev=[("tech-adept; she; throat slit by Kys", TVT), ("first name Lusinda", NOVEL("Ravenor"))]),
rec("brass-thief", form="construct", build="slight", marks=["mask"], attire=["helmet","armour-heavy"], carries=["sword"], palette=["#c9a227","#b5a642"], described="well",
    summary="Daemon bound into a clockwork body unfolded from a small gold-and-silver pyramid: thin, sheathed in segmented gold and brass plates, faceless save for eye slits in a high-crested helm, with 'rhyming swords' deploying from its forearms.",
    ev=[("'thin, wrapped in segmented plates of gold and brass, faceless but for eye slits in the high-crested helm'", "http://heresy-legions.blogspot.com/2009/07/brass-thief.html (search summary quoting Ravenor Returned)"),
        ("bound to a small gold and silver pyramid that unfolds into an armoured body; rhyming swords deploy from its forearms", TVT)]),
rec("toros-revoke", sex="male", ec="gold", described="partial",
    summary="Trice's psyker enforcer, noted for stale yellow pupils; no other physical description found.",
    ev=[("his pupils are stale yellow", TVT)]),
rec("ahenobarb", sex="male", build="massive", described="partial",
    summary="Kinsky's burly 'brute minder', called 'the giant' in the narration; his fist leaves a huge bruise on Thonius's face.",
    ev=[("'the giant'; 'brute minder'", NOVEL("Ravenor")), ("huge beatstick", TVT), ("burly minder", "research/raw_ravenor/src2.txt (lonepilgrim synopsis)")]),
rec("duboe", sex="male", described="partial",
    summary="Carnivora flect supplier, seen after capture as haggard and blood-flecked in chain binders; no further description.",
    ev=[("'haggard and blood-flecked', chain binders", NOVEL("Ravenor"))]),
rec("inquisitor-fenx", sex="male", attire=["armour-light"], palette=["#111111"], described="partial",
    summary="Inquisitor introduced as the man in black body armour; no face or hair details found.",
    ev=[("'The man in the black body armour' at his introduction", NOVEL("Ravenor Rogue"))]),
]
ids=[l.split()[0] for l in open(sys.argv[1]) if l.strip()]
got=[a["id"] for a in A]
assert sorted(ids)==sorted(got) and len(set(got))==len(got), (set(ids)^set(got))
json.dump({"appearance":A}, open(sys.argv[2],"w"), indent=2, ensure_ascii=False)
from collections import Counter; print(Counter(a["described"] for a in A))
